services:
  database:
    image: mysql:8
    container_name: database_e-learning
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e-learning
      MYSQL_USER: noctus
      MYSQL_PASSWORD: noctus
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_e-learning
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8080:8080"

volumes:
  mysql_data: {}
